services:
  - type: web
    name: bill-sharing-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true

databases:
  - name: billsharingdb
    plan: free
